version: '3.8'

services:
  arangodb:
    build:
      context: ../
      dockerfile: dockerfile.loc
    container_name: my-arangodb-container
    ports:
      - "8529:8529"
    networks:
      - app-network
            
networks:
  app-network:
    driver: bridge