version: '3.8'

services:
  arangodb:
    build:
      context: ../
      dockerfile: dockerfile.loc
    container_name: my-arangodb-container
    ports:
      - "8529:8529"
    networks:
      - arangodb-net

networks:
  arangodb-net:
    driver: bridge